namespace Hindsight;

/// <summary>
/// Selects where Hindsight writes history rows. Configured with
/// <see cref="HindsightOptionsBuilder.UseHistoryWriter(HistoryWriter)"/>; the default is
/// <see cref="Interceptor"/>. Both writers produce the same history schema and the same
/// half-open <c>[valid_from, valid_to)</c> intervals (DESIGN.md D3).
/// </summary>
public enum HistoryWriter
{
    /// <summary>
    /// A <c>SaveChangesInterceptor</c> in the application snapshots the tracked temporal entities and
    /// inserts history rows in the same transaction as the data change. The timestamp comes from the
    /// registered <see cref="System.TimeProvider"/>, one value per <c>SaveChanges</c>. This writer does
    /// not see <c>ExecuteUpdate</c>/<c>ExecuteDelete</c>, raw SQL, or writes from other processes
    /// (DESIGN.md D4). This is the default.
    /// </summary>
    Interceptor = 0,

    /// <summary>
    /// An <c>AFTER INSERT OR UPDATE OR DELETE</c> plpgsql trigger generated by the migration writes
    /// history rows, so it also captures <c>ExecuteUpdate</c>/<c>ExecuteDelete</c> and raw SQL.
    /// Not implemented yet — selecting it throws <see cref="System.NotSupportedException"/>; it arrives
    /// in a later release.
    /// </summary>
    Trigger = 1,
}
