// <auto-generated />
using System;
using InsuranceSample;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsuranceSample.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    [Migration("20260916204232_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InsuranceSample.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Premium")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Hindsight:IsExcluded", true);

                    b.HasKey("Id");

                    b.ToTable("policies", (string)null);

                    b
                        .HasAnnotation("Hindsight:HistoryEntityType", "InsuranceSample.Policy#History")
                        .HasAnnotation("Hindsight:IsTemporal", true);
                });

            modelBuilder.Entity("InsuranceSample.Policy#History", b =>
                {
                    b.Property<long>("history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("history_id"));

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("EffectiveFrom");

                    b.Property<int?>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasColumnName("Number");

                    b.Property<decimal?>("Premium")
                        .HasColumnType("numeric")
                        .HasColumnName("Premium");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<string>("changed_by")
                        .HasColumnType("text")
                        .HasColumnName("changed_by");

                    b.Property<string>("changed_by_name")
                        .HasColumnType("text")
                        .HasColumnName("changed_by_name");

                    b.Property<string>("correlation_id")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("extra")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra");

                    b.Property<short>("operation")
                        .HasColumnType("smallint")
                        .HasColumnName("operation");

                    b.Property<string>("reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("valid_from")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime>("valid_to")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to")
                        .HasDefaultValueSql("'infinity'::timestamp with time zone");

                    b.HasKey("history_id");

                    b.HasIndex(new[] { "Id", "valid_from" }, "ix_policies_history_version")
                        .IsDescending(false, true);

                    b.ToTable("policies_history", (string)null);

                    b.HasAnnotation("Hindsight:IsHistoryTable", true);
                });
#pragma warning restore 612, 618
        }
    }
}
