using Microsoft.EntityFrameworkCore;
using Npgsql;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Hindsight.IntegrationTests;

/// <summary>
/// A failed history write under <see cref="HistoryWriter.Interceptor"/> re-marks a previously
/// <c>Added</c> entity back to <c>Added</c> so a plain retry actually retries (see
/// <see cref="HistoryWriteFailureTests"/>). But by the time that happens, EF Core's own INSERT pipeline
/// has already propagated a real, database-generated value onto the entity's store-generated key
/// property — from the transaction that then rolled back. These tests pin down what a retried
/// <c>SaveChanges</c> does with that stale-but-real key value under each Npgsql identity strategy;
/// see [Limitations → Known trade-offs](../../docs/articles/limitations.md#known-trade-offs).
/// </summary>
[Collection(PostgresCollection.Name)]
public sealed class StoreGeneratedKeyRetryTests(PostgresFixture postgres)
{
    private static CancellationToken Ct => TestContext.Current.CancellationToken;

    [Fact]
    public async Task Retried_SaveChanges_with_IdentityByDefaultColumn_key_succeeds_reusing_the_rolled_back_id()
    {
        var cs = await postgres.CreateDatabaseAsync(
            nameof(Retried_SaveChanges_with_IdentityByDefaultColumn_key_succeeds_reusing_the_rolled_back_id), Ct);
        var provider = new RecordingChangeContextProvider(() => new ChangeContext { Extra = "not valid json" });
        await using var db = CreateContext<ByDefaultContext>(cs, provider);
        await db.Database.EnsureCreatedAsync(Ct);

        // Npgsql's convention default for a plain int PK against PostgreSQL 10+ — ground truth for the
        // premise of this test, not an assumption (CLAUDE.md rule 2).
        var strategy = db.Model.FindEntityType(typeof(Thing))!.FindProperty(nameof(Thing.Id))!
            .FindAnnotation("Npgsql:ValueGenerationStrategy")?.Value;
        Assert.Equal(NpgsqlValueGenerationStrategy.IdentityByDefaultColumn, strategy);

        var thing = new Thing { Name = "a" };
        db.Things.Add(thing);
        var entry = db.Entry(thing);

        await Assert.ThrowsAsync<PostgresException>(() => db.SaveChangesAsync(Ct));

        Assert.Equal(EntityState.Added, entry.State);
        Assert.NotEqual(0, thing.Id); // EF already wrote the generated id back before the rollback

        var idBeforeRetry = thing.Id;
        provider.Factory = () => ChangeContext.Empty;

        // The retry sends the stale id explicitly; GENERATED BY DEFAULT AS IDENTITY accepts it as-is —
        // no exception, no id renegotiation.
        await db.SaveChangesAsync(Ct);

        Assert.Equal(EntityState.Unchanged, entry.State);
        Assert.Equal(idBeforeRetry, thing.Id);
        Assert.Equal(idBeforeRetry, await ReadIdAsync(cs, "things"));

        // The rolled-back attempt still burned a sequence value (PostgreSQL sequences never roll back):
        // an unrelated Add afterwards observes a gap, not a collision with the reused id above.
        var another = new Thing { Name = "b" };
        db.Things.Add(another);
        await db.SaveChangesAsync(Ct);
        Assert.Equal(idBeforeRetry + 1, another.Id);
    }

    [Fact]
    public async Task Retried_SaveChanges_with_IdentityAlwaysColumn_key_fails_until_the_key_is_reset_to_default()
    {
        var cs = await postgres.CreateDatabaseAsync(
            nameof(Retried_SaveChanges_with_IdentityAlwaysColumn_key_fails_until_the_key_is_reset_to_default), Ct);
        var provider = new RecordingChangeContextProvider(() => new ChangeContext { Extra = "not valid json" });
        await using var db = CreateContext<AlwaysContext>(cs, provider);
        await db.Database.EnsureCreatedAsync(Ct);

        var thing = new Thing { Name = "a" };
        db.Things.Add(thing);
        var entry = db.Entry(thing);

        await Assert.ThrowsAsync<PostgresException>(() => db.SaveChangesAsync(Ct));

        Assert.Equal(EntityState.Added, entry.State);
        Assert.NotEqual(0, thing.Id); // same premise as the IdentityByDefaultColumn case

        provider.Factory = () => ChangeContext.Empty;

        // GENERATED ALWAYS AS IDENTITY rejects an explicit value outright (Postgres error 428C9,
        // "cannot insert a non-DEFAULT value into column"): EF Core does not notice the property is
        // store-generated and omit it from a retry's INSERT, so this is not the ByDefault case's silent
        // success — it is a loud, immediate, well-understood Postgres error, not silent corruption.
        var firstRetry = await Assert.ThrowsAsync<DbUpdateException>(() => db.SaveChangesAsync(Ct));
        Assert.IsType<PostgresException>(firstRetry.InnerException);
        Assert.Equal("428C9", ((PostgresException)firstRetry.InnerException).SqlState);
        Assert.Equal(EntityState.Added, entry.State);

        // The instance is now poisoned: nothing about the failure clears the stale id, so every further
        // retry on the same instance fails identically until the caller intervenes.
        var secondRetry = await Assert.ThrowsAsync<DbUpdateException>(() => db.SaveChangesAsync(Ct));
        Assert.Equal("428C9", ((PostgresException)secondRetry.InnerException!).SqlState);
        Assert.Equal(EntityState.Added, entry.State);

        // Resetting the key property back to its default is what actually unblocks the retry — EF Core
        // then omits it from the INSERT and lets Postgres generate a fresh value.
        thing.Id = 0;
        await db.SaveChangesAsync(Ct);

        Assert.Equal(EntityState.Unchanged, entry.State);
        Assert.NotEqual(0, thing.Id);
    }

    private static TContext CreateContext<TContext>(string connectionString, RecordingChangeContextProvider provider)
        where TContext : DbContext
    {
        var options = new DbContextOptionsBuilder<TContext>()
            .UseNpgsql(connectionString)
            .EnableServiceProviderCaching(false)
            .UseApplicationServiceProvider(new StubServiceProvider(provider))
            .UseHindsight(hb => hb
                .WithChangeContext<RecordingChangeContextProvider>()
                .UseHistoryWriter(HistoryWriter.Interceptor))
            .Options;

        return (TContext)Activator.CreateInstance(typeof(TContext), options)!;
    }

    private static async Task<int> ReadIdAsync(string connectionString, string table)
    {
        await using var conn = new NpgsqlConnection(connectionString);
        await conn.OpenAsync(Ct);
        await using var cmd = conn.CreateCommand();
        cmd.CommandText = $"select id from {table}";
        return (int)(await cmd.ExecuteScalarAsync(Ct))!;
    }

    private sealed class Thing
    {
        public int Id { get; set; }
        public string Name { get; set; } = "";
    }

    private sealed class StubServiceProvider(RecordingChangeContextProvider provider) : IServiceProvider
    {
        public object? GetService(Type serviceType) => serviceType == typeof(RecordingChangeContextProvider) ? provider : null;
    }

    // Registered on the application service provider (mirrors HistoryWriteFailureTests): the mutable
    // Factory lets a test flip between a failing and a succeeding ChangeContext without a new provider.
    private sealed class RecordingChangeContextProvider() : IChangeContextProvider
    {
        public RecordingChangeContextProvider(Func<ChangeContext> factory) : this() => Factory = factory;

        public Func<ChangeContext> Factory { get; set; } = () => ChangeContext.Empty;

        public ChangeContext GetChangeContext(DbContext context) => Factory();
    }

    private sealed class ByDefaultContext(DbContextOptions<ByDefaultContext> options) : DbContext(options)
    {
        public DbSet<Thing> Things => Set<Thing>();

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var thing = modelBuilder.Entity<Thing>();
            thing.ToTable("things");
            thing.Property(t => t.Id).HasColumnName("id");
            thing.Property(t => t.Name).HasColumnName("name");
            thing.IsTemporal();
            // No explicit ValueGenerationStrategy — Npgsql's own convention default for an int PK.
        }
    }

    private sealed class AlwaysContext(DbContextOptions<AlwaysContext> options) : DbContext(options)
    {
        public DbSet<Thing> Things => Set<Thing>();

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var thing = modelBuilder.Entity<Thing>();
            thing.ToTable("things");
            thing.Property(t => t.Id).HasColumnName("id").UseIdentityAlwaysColumn();
            thing.Property(t => t.Name).HasColumnName("name");
            thing.IsTemporal();
        }
    }
}
