CREATE TABLE categories (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    CONSTRAINT "PK_categories" PRIMARY KEY (id)
);


CREATE TABLE nodes_history (
    history_id bigint GENERATED ALWAYS AS IDENTITY,
    category_id integer,
    changed_by text,
    changed_by_name text,
    correlation_id text,
    extra jsonb,
    id integer,
    name text,
    operation smallint NOT NULL,
    parent_id integer,
    reason text,
    valid_from timestamp with time zone NOT NULL,
    valid_to timestamp with time zone NOT NULL DEFAULT ('infinity'::timestamp with time zone),
    CONSTRAINT "PK_nodes_history" PRIMARY KEY (history_id)
);


CREATE INDEX ix_nodes_history_period ON nodes_history USING gist (tstzrange(valid_from, valid_to));


CREATE TABLE nodes (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    category_id integer NOT NULL,
    parent_id integer,
    CONSTRAINT "PK_nodes" PRIMARY KEY (id),
    CONSTRAINT "FK_nodes_categories_category_id" FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE,
    CONSTRAINT "FK_nodes_nodes_parent_id" FOREIGN KEY (parent_id) REFERENCES nodes (id)
);


CREATE OR REPLACE FUNCTION nodes_history_write() RETURNS trigger
LANGUAGE plpgsql AS $hindsight$
DECLARE
    _now timestamp with time zone := now();
    _closed_at timestamp with time zone;
    _changed_by text := nullif(current_setting('hindsight.changed_by', true), '');
    _changed_by_name text := nullif(current_setting('hindsight.changed_by_name', true), '');
    _correlation_id text := nullif(current_setting('hindsight.correlation_id', true), '');
    _reason text := nullif(current_setting('hindsight.reason', true), '');
    _extra jsonb := nullif(current_setting('hindsight.extra', true), '')::jsonb;
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO nodes_history (category_id, id, name, parent_id, valid_from, valid_to, operation, changed_by, changed_by_name, correlation_id, reason, extra)
        VALUES (NEW.category_id, NEW.id, NEW.name, NEW.parent_id, _now, 'infinity'::timestamp with time zone, 1, _changed_by, _changed_by_name, _correlation_id, _reason, _extra);
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        IF (NEW.category_id, NEW.id, NEW.name, NEW.parent_id) IS NOT DISTINCT FROM (OLD.category_id, OLD.id, OLD.name, OLD.parent_id) THEN
            RETURN NEW;
        END IF;
        UPDATE nodes_history SET valid_to = GREATEST(_now, valid_from + INTERVAL '1 microsecond') WHERE id = OLD.id AND valid_to = 'infinity'::timestamp with time zone RETURNING valid_to INTO _closed_at;
        INSERT INTO nodes_history (category_id, id, name, parent_id, valid_from, valid_to, operation, changed_by, changed_by_name, correlation_id, reason, extra)
        VALUES (NEW.category_id, NEW.id, NEW.name, NEW.parent_id, COALESCE(_closed_at, _now), 'infinity'::timestamp with time zone, 2, _changed_by, _changed_by_name, _correlation_id, _reason, _extra);
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE nodes_history SET valid_to = GREATEST(_now, valid_from + INTERVAL '1 microsecond') WHERE id = OLD.id AND valid_to = 'infinity'::timestamp with time zone RETURNING valid_to INTO _closed_at;
        INSERT INTO nodes_history (category_id, id, name, parent_id, valid_from, valid_to, operation, changed_by, changed_by_name, correlation_id, reason, extra)
        VALUES (OLD.category_id, OLD.id, OLD.name, OLD.parent_id, COALESCE(_closed_at, _now), COALESCE(_closed_at, _now), 3, _changed_by, _changed_by_name, _correlation_id, _reason, _extra);
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$hindsight$;


CREATE OR REPLACE TRIGGER nodes_history_trg AFTER INSERT OR UPDATE OR DELETE ON nodes FOR EACH ROW EXECUTE FUNCTION nodes_history_write();


INSERT INTO nodes_history (category_id, id, name, parent_id, valid_from, valid_to, operation)
SELECT category_id, id, name, parent_id, now(), 'infinity', 1
FROM nodes;


CREATE INDEX "IX_nodes_category_id" ON nodes (category_id);


CREATE INDEX "IX_nodes_parent_id" ON nodes (parent_id);


CREATE INDEX ix_nodes_history_version ON nodes_history (id, valid_from DESC);
