using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql;

namespace Hindsight.IntegrationTests;

/// <summary>
/// The <see cref="HistoryWriter.Trigger"/> DDL, generated by <c>HindsightMigrationsSqlGenerator</c> from
/// the same <c>Hindsight:*</c> annotations the history table is built from (DESIGN.md D3), then applied
/// to a real database. The generated function + trigger SQL has a Verify snapshot; the applied schema is
/// inspected through <c>pg_proc</c> / <c>pg_trigger</c> / <c>information_schema</c>. This is the spike
/// that proved the trigger can be emitted through EF Core public API only (2026-09-11).
/// </summary>
[Collection(PostgresCollection.Name)]
public sealed class TriggerDdlTests(PostgresFixture postgres)
{
    private static CancellationToken Ct => TestContext.Current.CancellationToken;

    [Fact]
    public async Task Trigger_ddl_has_the_expected_shape()
    {
        await using var db = Build("unused");
        var sql = string.Join("\n\n", TriggerCommands(db));

        await Verify(sql, extension: "sql");
    }

    [Fact]
    public async Task Generated_trigger_writes_half_open_history_for_raw_sql_writes()
    {
        var cs = await postgres.CreateDatabaseAsync(nameof(Generated_trigger_writes_half_open_history_for_raw_sql_writes), Ct);
        await using (var db = Build(cs))
        {
            await ApplySchemaAsync(db, cs);
        }

        // Raw SQL only: no EF, no interceptor. The trigger is the only thing writing history.
        await using var conn = new NpgsqlConnection(cs);
        await conn.OpenAsync(Ct);

        await ExecAsync(conn, "insert into policies (id, number, status, premium) values (1, 'ACME-1', 'Draft', 100)");
        await ExecAsync(conn, "update policies set status = 'Active', premium = 250 where id = 1");
        await ExecAsync(conn, "update policies set premium = 300 where id = 1");
        await ExecAsync(conn, "delete from policies where id = 1");

        var rows = await ReadHistoryAsync(conn);

        Assert.Equal([1, 2, 2, 3], rows.Select(r => r.Operation));
        // contiguous half-open intervals, exactly one 'infinity' while live, none after delete
        for (var i = 1; i < rows.Count; i++)
        {
            Assert.True(rows[i - 1].ValidTo <= rows[i].ValidFrom, $"row {i} starts before the previous one closed");
        }

        Assert.Equal(3, rows.Count(r => r.Operation != 3));
        Assert.DoesNotContain(rows, r => r.IsOpen);                 // deleted entity: zero open versions
        var tombstone = rows[^1];
        Assert.Equal(3, tombstone.Operation);
        Assert.Equal(tombstone.ValidFrom, tombstone.ValidTo);        // empty [ts, ts)
        Assert.Equal("Active", rows[1].Status);
        Assert.Equal(300m, rows[2].Premium);
    }

    [Fact]
    public async Task Applied_schema_has_the_function_and_the_trigger()
    {
        var cs = await postgres.CreateDatabaseAsync(nameof(Applied_schema_has_the_function_and_the_trigger), Ct);
        await using var db = Build(cs);
        await ApplySchemaAsync(db, cs);

        await using var conn = new NpgsqlConnection(cs);
        await conn.OpenAsync(Ct);

        var function = await ScalarAsync(conn,
            "select count(*) from pg_proc where proname = 'policies_history_write'");
        Assert.Equal(1L, function);

        var trigger = await ScalarAsync(conn,
            """
            select count(*) from pg_trigger t
            join pg_class c on c.oid = t.tgrelid
            where t.tgname = 'policies_history_trg' and c.relname = 'policies' and not t.tgisinternal
            """);
        Assert.Equal(1L, trigger);
    }

    [Fact]
    public async Task Adding_a_column_re_emits_create_or_replace_function_without_touching_history()
    {
        await using var v1 = Build("unused");
        var v1Model = v1.GetService<IDesignTimeModel>().Model;

        await using var v2 = Build("unused", withNotes: true);
        var v2Model = v2.GetService<IDesignTimeModel>().Model;

        var operations = v2.GetService<IMigrationsModelDiffer>().GetDifferences(
            v1Model.GetRelationalModel(), v2Model.GetRelationalModel());

        var commands = v2.GetService<IMigrationsSqlGenerator>().Generate(operations, v2Model)
            .Select(command => command.CommandText)
            .ToList();

        Assert.Contains(commands, text =>
            text.Contains("ALTER TABLE policies_history ADD notes", StringComparison.Ordinal));
        Assert.Contains(commands, text =>
            text.Contains("CREATE OR REPLACE FUNCTION", StringComparison.Ordinal)
            && text.Contains("policies_history_write", StringComparison.Ordinal)
            && text.Contains("NEW.notes", StringComparison.Ordinal));
        Assert.DoesNotContain(commands, text =>
            text.Contains("DROP COLUMN", StringComparison.OrdinalIgnoreCase)
            && text.Contains("policies_history", StringComparison.Ordinal));
    }

    private static IEnumerable<string> TriggerCommands(TriggerContext db)
    {
        var model = db.GetService<IDesignTimeModel>().Model;
        var operations = db.GetService<IMigrationsModelDiffer>().GetDifferences(null, model.GetRelationalModel());
        return db.GetService<IMigrationsSqlGenerator>().Generate(operations, model)
            .Select(command => command.CommandText)
            .Where(text => text.Contains("policies_history_write", StringComparison.Ordinal)
                || text.Contains("policies_history_trg", StringComparison.Ordinal));
    }

    private static async Task ApplySchemaAsync(TriggerContext db, string connectionString)
    {
        var model = db.GetService<IDesignTimeModel>().Model;
        var operations = db.GetService<IMigrationsModelDiffer>().GetDifferences(null, model.GetRelationalModel());
        var commands = db.GetService<IMigrationsSqlGenerator>().Generate(operations, model);

        await using var conn = new NpgsqlConnection(connectionString);
        await conn.OpenAsync(Ct);
        foreach (var command in commands)
        {
            await ExecAsync(conn, command.CommandText);
        }
    }

    private static async Task ExecAsync(NpgsqlConnection conn, string sql)
    {
        await using var cmd = conn.CreateCommand();
        cmd.CommandText = sql;
        await cmd.ExecuteNonQueryAsync(Ct);
    }

    private static async Task<long> ScalarAsync(NpgsqlConnection conn, string sql)
    {
        await using var cmd = conn.CreateCommand();
        cmd.CommandText = sql;
        return (long)(await cmd.ExecuteScalarAsync(Ct))!;
    }

    private static async Task<List<HistoryRow>> ReadHistoryAsync(NpgsqlConnection conn)
    {
        await using var cmd = conn.CreateCommand();
        cmd.CommandText =
            """
            select status, premium, valid_from, valid_to, operation
            from policies_history where id = 1
            order by valid_from, history_id
            """;

        var rows = new List<HistoryRow>();
        await using var reader = await cmd.ExecuteReaderAsync(Ct);
        while (await reader.ReadAsync(Ct))
        {
            rows.Add(new HistoryRow(
                reader.GetString(0),
                reader.GetDecimal(1),
                reader.GetFieldValue<DateTime>(2),
                reader.GetFieldValue<DateTime>(3),
                reader.GetInt16(4)));
        }

        return rows;
    }

    private static TriggerContext Build(string connectionString, bool withNotes = false)
    {
        var options = new DbContextOptionsBuilder<TriggerContext>()
            .UseNpgsql(connectionString)
            .ReplaceService<IModelCacheKeyFactory, NotesAwareModelCacheKeyFactory>()
            .UseHindsight(h => h.UseHistoryWriter(HistoryWriter.Trigger))
            .Options;
        return new TriggerContext(options, withNotes);
    }

    private sealed record HistoryRow(string Status, decimal Premium, DateTime ValidFrom, DateTime ValidTo, short Operation)
    {
        public bool IsOpen => ValidTo == DateTime.MaxValue;
    }

    private sealed class Policy
    {
        public int Id { get; set; }
        public string Number { get; set; } = "";
        public string Status { get; set; } = "Draft";
        public decimal Premium { get; set; }
        public string? Notes { get; set; }
    }

    // The two schema versions live under one context type, so EF would cache one model for both;
    // key the cache on the flag that actually differs.
    private sealed class NotesAwareModelCacheKeyFactory : IModelCacheKeyFactory
    {
        public object Create(DbContext context, bool designTime)
            => (context.GetType(), ((TriggerContext)context).WithNotes, designTime);
    }

    private sealed class TriggerContext(DbContextOptions<TriggerContext> options, bool withNotes) : DbContext(options)
    {
        private readonly bool _withNotes = withNotes;

        public bool WithNotes => _withNotes;

        public DbSet<Policy> Policies => Set<Policy>();

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var policy = modelBuilder.Entity<Policy>();
            policy.ToTable("policies");
            policy.Property(p => p.Id).HasColumnName("id").ValueGeneratedNever();
            policy.Property(p => p.Number).HasColumnName("number");
            policy.Property(p => p.Status).HasColumnName("status");
            policy.Property(p => p.Premium).HasColumnName("premium").HasPrecision(18, 4);
            if (_withNotes)
            {
                policy.Property(p => p.Notes).HasColumnName("notes");
            }
            else
            {
                policy.Ignore(p => p.Notes);
            }

            policy.IsTemporal();
        }
    }
}
